import { calculateCredits } from '@config/credits';

import { TimeTableCourse } from '@/types';

export const TIMETABLE_DATA: TimeTableCourse[] = [
  {
    courseCode: 'CHD405',
    courseName: 'Energy Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'CHE-401' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'CHE-401' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'CHE-401' },
    ],
  },
  {
    courseCode: 'CHD415',
    courseName: 'Interfacial Phenomena and Microfluidics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
    ],
  },
  {
    courseCode: 'CHD418',
    courseName: 'Electrochemical Science and Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'CHE-401' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'CHE-401' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'CHE-401' },
    ],
  },
  {
    courseCode: 'CHO403',
    courseName: 'Process Intensification',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'CHE-423' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'CHE-423' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'CHE-423' },
    ],
  },
  {
    courseCode: 'hsd562',
    courseName: 'Myth Studies in Popular Culture',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'hsd564',
    courseName: 'Health, Culture, and Humanities',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'HSO413',
    courseName: 'AI and Educational Technology: An Introduction',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'HSO513',
    courseName: 'Environment, Development and Politics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSD401',
    courseName: 'Advanced Algorithms',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G8' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G8' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'CSD513',
    courseName: 'Internet of Things',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G7' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G7' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G7' },
    ],
  },
  {
    courseCode: 'CSO502',
    courseName: 'Data Analytics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G12' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G12' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G12' },
    ],
  },
  {
    courseCode: 'CSO508',
    courseName: 'Building Software Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
    ],
  },
  {
    courseCode: 'CED531',
    courseName: 'Advanced Design of Structures',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
    ],
  },
  {
    courseCode: 'CED533',
    courseName: 'Hydroclimatology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C10' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C10' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C10' },
    ],
  },
  {
    courseCode: 'CEO527',
    courseName: 'Bridge Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C8' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C8' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C8' },
    ],
  },
  {
    courseCode: 'CEO528',
    courseName: 'Ground Improvement and Geosynthetics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C6' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C6' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C6' },
    ],
  },
  {
    courseCode: 'ECD404',
    courseName: 'Digital Image Processing',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C11' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C11' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C11' },
    ],
  },
  {
    courseCode: 'ECD406',
    courseName: 'EDA for VLSI Design',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C11' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C11' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C11' },
    ],
  },
  {
    courseCode: 'ECD413',
    courseName: 'Microelectronics Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C12' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C12' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C12' },
    ],
  },
  {
    courseCode: 'ECD419',
    courseName: 'Satellite Communication',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C12' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C12' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C12' },
    ],
  },
  {
    courseCode: 'ECD501',
    courseName: 'Metamaterials and CRLH Transmission Lines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C10' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C10' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C10' },
    ],
  },
  {
    courseCode: 'ECD564',
    courseName: 'On-Chip Interconnects',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C4' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-I-C4' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-I-C4' },
    ],
  },
  {
    courseCode: 'ECO401',
    courseName: 'UAV Sensors',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C12' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C12' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C12' },
    ],
  },
  {
    courseCode: 'ECO520',
    courseName: 'Optical Networks',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C6' },
    ],
  },
  {
    courseCode: 'EED405',
    courseName: 'Instrumentation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'EED406',
    courseName: 'Special Purpose Electric Machines and Drives',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'EEO406',
    courseName: 'Modern Sensors and Signal Conditioning Circuits',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'EEO407',
    courseName: 'Condition Monitoring of Electrical Machines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'ESD406',
    courseName: 'Environmental Nano Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C9' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C9' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C9' },
    ],
  },
  {
    courseCode: 'ESD503',
    courseName: 'Environmental Modelling',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G11' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G11' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G11' },
    ],
  },
  {
    courseCode: 'ESD505',
    courseName: 'Advanced Water and Wastewater Treatment',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C9' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C9' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C9' },
    ],
  },
  {
    courseCode: 'ESO505',
    courseName: 'Climate Change and Modelling',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C16' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C16' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C16' },
    ],
  },
  {
    courseCode: 'MSO403',
    courseName: 'Foundations of Management and Organizational Behaviour',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G8' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G8' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'FMD462',
    courseName: 'Process Control and Plant Layout',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C14' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C14' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C14' },
    ],
  },
  {
    courseCode: 'FMD522',
    courseName: 'Coal Preparation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C14' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C14' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C14' },
    ],
  },
  {
    courseCode: 'FMD536',
    courseName: 'Surface Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'FME-1' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'FME-1' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'FME-1' },
    ],
  },
  {
    courseCode: 'FMO544',
    courseName: 'Clean Coal Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C14' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C14' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C14' },
    ],
  },
  {
    courseCode: 'HSO513',
    courseName: 'Environment, Development and Politics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G7' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G7' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G7' },
    ],
  },
  {
    courseCode: 'HSO308',
    courseName: 'Social Psychology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'HSO310',
    courseName: 'Psychology of Everyday Life',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C13' },
    ],
  },
  {
    courseCode: 'MND407',
    courseName: 'Underground Space Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G13' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G13' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'MND408',
    courseName: 'Innovative Mining Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G12' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G12' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G12' },
    ],
  },
  {
    courseCode: 'MND409',
    courseName: 'Introduction to Geographical Information System',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G12' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G12' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G12' },
    ],
  },
  {
    courseCode: 'MND411',
    courseName: 'Advanced Underground Mining Methods',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G12' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G12' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G12' },
    ],
  },
  {
    courseCode: 'MND412',
    courseName: 'Deep Coal Mining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G13' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G13' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'MSO404',
    courseName: 'Introduction to Operations Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G7' },
    ],
  },
  {
    courseCode: 'MED529',
    courseName: 'Composite Materials',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G10' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'MED531',
    courseName: 'Fracture Mechanics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G10' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'MEO522',
    courseName: 'Condition Monitoring of Machines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G10' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'MEO580',
    courseName: 'Measurements in Thermal Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'MED521',
    courseName: 'Theory of Lubrication',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'MME-C1' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'MME-C1' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'MME-C1' },
    ],
  },
  {
    courseCode: 'MEO579',
    courseName: 'Computational Fluid Dynamics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'MECH-G2' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'MECH-G2' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'MECH-G2' },
    ],
  },
  {
    courseCode: 'MEO581',
    courseName: 'Fundamentals of Combustion',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C1' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C1' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'LC-II-C1' },
    ],
  },
  {
    courseCode: 'MMD505',
    courseName: 'Fluid Flow Machines in Mines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G9' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G9' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-G9' },
    ],
  },
  {
    courseCode: 'PED405',
    courseName: 'Pipeline Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'PET 3' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'PET 3' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'PET 3' },
    ],
  },
  {
    courseCode: 'PED406',
    courseName: 'Reservoir Modeling and Simulation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'PET 4' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'PET 4' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'PET 4' },
    ],
  },
  {
    courseCode: 'PEO405',
    courseName: 'Integrated Reservoir Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'PET 2' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'PET 2' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'PET 2' },
    ],
  },
  {
    courseCode: 'PEO506',
    courseName: 'Carbon Capture And Sequestration',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: 'PET 1' },
      { day: 'Thursday', startTime: '14:00', endTime: '14:50', venue: 'PET 1' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: 'PET 1' },
    ],
  },
  {
    courseCode: 'PHD503',
    courseName: 'High Energy Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C7' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C7' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C7' },
    ],
  },
  {
    courseCode: 'PHD511',
    courseName: 'Astrophysics and Cosmology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C7' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C7' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C7' },
    ],
  },
  {
    courseCode: 'PHD512',
    courseName: 'Nonlinear Optics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C15' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C15' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C15' },
    ],
  },
  {
    courseCode: 'PHD513',
    courseName: 'Semiconductor Physics and Technology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C15' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C15' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C15' },
    ],
  },
  {
    courseCode: 'PHD571',
    courseName: 'Advanced Mathematical Methods in Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C15' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C15' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C15' },
    ],
  },
  {
    courseCode: 'PHO503',
    courseName: 'Physics of Nanomaterials',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C7' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C7' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C7' },
    ],
  },
  {
    courseCode: 'PHO505',
    courseName: 'Quantum Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHO572',
    courseName: 'Photonics and Fibre Optics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'AGL-1' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'AGL-1' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'AGL-1' },
    ],
  },
  {
    courseCode: 'CHC306',
    courseName: 'Chemical Process Equipment Design',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'PET 2' }],
  },
  {
    courseCode: 'CHC307',
    courseName: 'Process Modelling and Simulation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'PET 2' }],
  },
  {
    courseCode: 'CHC308',
    courseName: 'Chemical Process Equipment Design Lab',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'CSE LAB -IV' },
    ],
  },
  {
    courseCode: 'CHC309',
    courseName: 'Process Simulation Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'CSE LAB - III' }],
  },
  {
    courseCode: 'CHD408',
    courseName: 'Process Data Analytics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C4' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C4' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C4' },
    ],
  },
  {
    courseCode: 'CHO301',
    courseName: 'Petroleum Refining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'PET 2' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'PET 2' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'PET 2' },
    ],
  },
  {
    courseCode: 'CHO404',
    courseName: 'AI in Process Industries',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C14' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C14' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C14' },
    ],
  },
  {
    courseCode: 'hsd561',
    courseName: 'History and Philosophy of Science',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC305',
    courseName: 'Computer Networks',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'NAC Hall' }],
  },
  {
    courseCode: 'CSC306',
    courseName: 'Software Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'NAC Hall' }],
  },
  {
    courseCode: 'CSC307',
    courseName: 'Computer Networks Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Friday', startTime: '09:00', endTime: '09:50', venue: 'NLHC Computer Lab - I' },
      { day: 'Friday', startTime: '08:00', endTime: '08:50', venue: 'NLHC Computer Lab - I' },
    ],
  },
  {
    courseCode: 'CSC308',
    courseName: 'Software Engineering Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: 'NLHC Computer Lab - III' },
      { day: 'Thursday', startTime: '08:00', endTime: '08:50', venue: 'NLHC Computer Lab - III' },
    ],
  },
  {
    courseCode: 'CSO302',
    courseName: 'Graph Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'NAC Hall' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'NAC Hall' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'NAC Hall' },
    ],
  },
  {
    courseCode: 'CSO503',
    courseName: 'Data Mining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G8' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'CSO506',
    courseName: 'Principles of Blockchain Technologies',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'NAC Hall' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'NAC Hall' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'NAC Hall' },
    ],
  },
  {
    courseCode: 'CEC305',
    courseName: 'Design of Steel Structures',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C8' }],
  },
  {
    courseCode: 'CEC306',
    courseName: 'Water Resources Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C8' }],
  },
  {
    courseCode: 'CEC307',
    courseName: 'Structural Detailing Laboratory',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'CSE LAB - III' }],
  },
  {
    courseCode: 'CEC308',
    courseName: 'Water Resources Engineering Laboratory',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'CEUG3' }],
  },
  {
    courseCode: 'CED403',
    courseName: 'Advanced Hydrology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C6' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C6' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C6' },
    ],
  },
  {
    courseCode: 'CEO303',
    courseName: 'Construction Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G7' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G7' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G7' },
    ],
  },
  {
    courseCode: 'CEO402',
    courseName: 'Optimization Methods',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC306',
    courseName: 'Digital Communication',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G16' }],
  },
  {
    courseCode: 'ECC307',
    courseName: 'Microwave Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G16' }],
  },
  {
    courseCode: 'ECC308',
    courseName: 'Digital Communication Lab',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC309',
    courseName: 'Microwave Engineering Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      {
        day: 'Thursday',
        startTime: '08:00',
        endTime: '08:50',
        venue: 'Microwave & Antenna Lab (232)',
      },
      {
        day: 'Thursday',
        startTime: '09:00',
        endTime: '09:50',
        venue: 'Microwave & Antenna Lab (232)',
      },
    ],
  },
  {
    courseCode: 'ECD409',
    courseName: 'Fiber Optics and Laser Instrumentation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G16' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G16' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G16' },
    ],
  },
  {
    courseCode: 'ECO302',
    courseName: 'Power Electronics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'ECO400',
    courseName: 'Stochastic Methods in Data Science',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G16' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G16' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G16' },
    ],
  },
  {
    courseCode: 'EEC311',
    courseName: 'Power System Analysis and Control',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G15' }],
  },
  {
    courseCode: 'EEC312',
    courseName: 'Electrical Drives and Applications',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G15' }],
  },
  {
    courseCode: 'EEC377',
    courseName: 'Power and Switchgear Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'PS Lab' }],
  },
  {
    courseCode: 'EEC378',
    courseName: 'Power Electronics and Drives lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'Drives Lab' }],
  },
  {
    courseCode: 'EED404',
    courseName: 'Reactive Power and Voltage Control',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'EEO301',
    courseName: 'Microprocessor & Microcontroller',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'EEO302',
    courseName: 'Industrial Utilization of Electrical Power',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'ESC311',
    courseName: 'Solid Waste Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C5' }],
  },
  {
    courseCode: 'ESC312',
    courseName: 'Geoinformatics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C16' },
      { day: 'Wednesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C16' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C16' },
    ],
  },
  {
    courseCode: 'ESC357',
    courseName: 'Solid Waste Management Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'Wastewater Lab' }],
  },
  {
    courseCode: 'ESC358',
    courseName: 'Geoinformatics Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: 'Remote Sensing & GIS Lab' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'Remote Sensing & GIS Lab' },
    ],
  },
  {
    courseCode: 'ESD402',
    courseName: 'Industrial Waste Water Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G8' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'ESD404',
    courseName: 'Water Resource Planning and Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G8' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'ESO301',
    courseName: 'Applied Statistics for Environmental Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G8' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G8' },
    ],
  },
  {
    courseCode: 'MSO301',
    courseName: 'Operations Research',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'MSO401',
    courseName: 'Principles of Economics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'MSO402',
    courseName: 'Introduction to Financial Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'FMC303',
    courseName: 'Mechanical Metallurgy',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C14' }],
  },
  {
    courseCode: 'FMC304',
    courseName: 'Coal and Mineral Processing Plant Design',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C14' }],
  },
  {
    courseCode: 'FMC305',
    courseName: 'Coal and Mineral Processing Plant Design Laboratory',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' }],
  },
  {
    courseCode: 'FMC352',
    courseName: 'Heat Treatment and Mechanical Metallurgy Laboratory',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'FMD402',
    courseName: 'Welding Metallurgy',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C9' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C9' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C9' },
    ],
  },
  {
    courseCode: 'FMD463',
    courseName: 'Non Ferrous Extractive Metallurgy',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G10' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'FMD525',
    courseName: 'Iron and Steel Making',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C14' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C14' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C14' },
    ],
  },
  {
    courseCode: 'HSD530',
    courseName: 'Indian Philosophy of Mind',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G14' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G14' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G14' },
    ],
  },
  {
    courseCode: 'MNC304',
    courseName: 'Mine Legislation and Safety',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G10' }],
  },
  {
    courseCode: 'MNC305',
    courseName: 'Mine Automation and Data Analytics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G13' }],
  },
  {
    courseCode: 'MNC306',
    courseName: 'Mine Data Analytics Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'CAMPAD Lab' }],
  },
  {
    courseCode: 'MNC307',
    courseName: 'Numerical Modelling/Remote Sensing & GIS Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' }],
  },
  {
    courseCode: 'MNO302',
    courseName: 'Seabed Mining and Asteroid Mining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G13' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G13' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'MNO304',
    courseName: 'Coal Mine Methane Recovery and Utilization',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G13' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G13' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'MNO401',
    courseName: 'Rock Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G13' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G13' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'HSO402',
    courseName: 'Computational Psychology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'HSO404',
    courseName: 'Sociology of Health',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G15' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G15' },
    ],
  },
  {
    courseCode: 'MEC306',
    courseName: 'Computer Aided Manufacturing',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G14' }],
  },
  {
    courseCode: 'MEC307',
    courseName: 'IC Engines and Gas Turbines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G14' }],
  },
  {
    courseCode: 'MEC308',
    courseName: 'Computer Aided Manufacturing Lab',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'MEC309',
    courseName: 'Heat Power and Refrigeration Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Thursday', startTime: '08:00', endTime: '08:50', venue: '' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'MEO301',
    courseName: 'Mechanical Measurements',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G14' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G14' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G14' },
    ],
  },
  {
    courseCode: 'MEO402',
    courseName: 'Optimization Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G16' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G16' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G16' },
    ],
  },
  {
    courseCode: 'MEO584',
    courseName: 'Waste Heat Utilization',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'HSD565',
    courseName: 'AI and Spirituality: An Introduction',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: '' },
    ],
  },
  {
    courseCode: 'HSO412',
    courseName: 'Theories of Acting',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'MMC305',
    courseName: 'Underground Mining Equipment',
    ltp: '3-1-0',
    credits: calculateCredits('3-1-0'),
    slots: [
      { day: 'Monday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Tuesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C19' },
    ],
  },
  {
    courseCode: 'MMC306',
    courseName: 'Opencast Mining Equipment',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C19' }],
  },
  {
    courseCode: 'MMC307',
    courseName: 'Mining Machinery Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'MH- LAB' }],
  },
  {
    courseCode: 'MMC308',
    courseName: 'Pumps Fans & Compressors Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: 'PFC LAB' },
      { day: 'Thursday', startTime: '08:00', endTime: '08:50', venue: 'PFC LAB' },
    ],
  },
  {
    courseCode: 'MMD508',
    courseName: 'Mechatronics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C19' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C19' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C19' },
    ],
  },
  {
    courseCode: 'HSD504',
    courseName: 'Applied Linguistics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'PET 3' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'PET 3' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'PET 3' },
    ],
  },
  {
    courseCode: 'HSO514',
    courseName: 'Introduction to Climate Change and Society',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'PET 1' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'PET 1' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'PET 1' },
    ],
  },
  {
    courseCode: 'PEC306',
    courseName: 'Directional Drilling',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'PET 1' }],
  },
  {
    courseCode: 'PEC307',
    courseName: 'Oil and Gas Well Testing',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'PET 1' }],
  },
  {
    courseCode: 'PEC308',
    courseName: 'Enhanced Oil Recovery Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      {
        day: 'Friday',
        startTime: '11:00',
        endTime: '11:50',
        venue: 'PE Reservoir Engineering laboratory',
      },
    ],
  },
  {
    courseCode: 'PEC309',
    courseName: 'Reservoir Characterization Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' }],
  },
  {
    courseCode: 'PED504',
    courseName: 'Profile Modification & Water Shutoff',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'PET 1' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'PET 1' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'PET 1' },
    ],
  },
  {
    courseCode: 'PEO302',
    courseName: 'Oil & Gas Field Development and Planning',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'PET 1' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'PET 1' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'PET 1' },
    ],
  },
  {
    courseCode: 'PHC302',
    courseName: 'Solid State Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [{ day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C4' }],
  },
  {
    courseCode: 'PHC303',
    courseName: 'Applied Optics Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'PHUG LAB-2' }],
  },
  {
    courseCode: 'PHC304',
    courseName: 'Spectroscopy Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [{ day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'PHUG LAB-2' }],
  },
  {
    courseCode: 'PHC510',
    courseName: 'Atomic and Molecular Physics',
    ltp: '3-1-0',
    credits: calculateCredits('3-1-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Tuesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-C4' },
    ],
  },
  {
    courseCode: 'PHO301',
    courseName: 'Low Temperature Physics & Superconductivity',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHO303',
    courseName: 'Physics for Society',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'PHO401',
    courseName: 'Introduction to Quantum Devices',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'PHO403',
    courseName: 'Energy Storage Technologies',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C15' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C15' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C15' },
    ],
  },
  {
    courseCode: 'GLC513',
    courseName: 'Coal Geology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G10' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'GLC516',
    courseName: 'Coal Geology Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Wednesday', startTime: '16:00', endTime: '16:50', venue: 'Coal Geology Lab' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: 'Coal Geology Lab' },
    ],
  },
  {
    courseCode: 'GLC526',
    courseName: 'Ore Geology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'AGL-3' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'AGL-3' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: 'AGL-3' },
    ],
  },
  {
    courseCode: 'GLC533',
    courseName: 'Ore Geology Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'Ore Geology Lab' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'Ore Geology Lab' },
    ],
  },
  {
    courseCode: 'GLD531',
    courseName: 'Sequence Stratigraphy and Basin Analysis',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'AGL-2' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'AGL-2' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'AGL-2' },
    ],
  },
  {
    courseCode: 'GLD544',
    courseName: 'Kinematics of Rock Deformation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Tuesday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Wednesday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLO502',
    courseName: 'Geoarchaeology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'GPC520',
    courseName: 'Magnetic Method',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'AGP 516' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'AGP 516' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: 'AGP 516' },
    ],
  },
  {
    courseCode: 'GPC521',
    courseName: 'Geoelectromagnetic Method',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'AGP Annexure Ground Floor' },
      {
        day: 'Wednesday',
        startTime: '11:00',
        endTime: '11:50',
        venue: 'AGP Annexure Ground Floor',
      },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPC522',
    courseName: 'Magnetic Method Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPC523',
    courseName: 'Geoelectromagnetic Method Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      {
        day: 'Wednesday',
        startTime: '16:00',
        endTime: '16:50',
        venue: 'AGP Annexure Ground Floor',
      },
      {
        day: 'Wednesday',
        startTime: '15:00',
        endTime: '15:50',
        venue: 'AGP Annexure Ground Floor',
      },
    ],
  },
  {
    courseCode: 'GPD502',
    courseName: 'Formation Evaluation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPD508',
    courseName: 'Seismological Data Analysis',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'Seismic data processing Lab' },
      {
        day: 'Thursday',
        startTime: '11:00',
        endTime: '11:50',
        venue: 'Seismic data processing Lab',
      },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'Seismic data processing Lab' },
    ],
  },
  {
    courseCode: 'GPD510',
    courseName: 'Reservoir Geophysics and Deep Water Imaging',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'AGP 516' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'AGP 516' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'AGP 516' },
    ],
  },
  {
    courseCode: 'GPO510',
    courseName: 'Strong Motion Seismology and Structural Responses',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'AGP 516' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'AGP 516' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'AGP 516' },
    ],
  },
  {
    courseCode: 'MCC401',
    courseName: 'Software Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C20' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'LC-II-C20' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C20' },
    ],
  },
  {
    courseCode: 'MCC402',
    courseName: 'Software Engineering Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'UG Lab-2' },
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'UG Lab-2' },
    ],
  },
  {
    courseCode: 'MCD505',
    courseName: 'Basic Number Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'MCD510',
    courseName: 'Complex Analysis',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C20' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'LC-II-C20' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: 'LC-II-C20' },
    ],
  },
  {
    courseCode: 'MCD514',
    courseName: 'Sampling Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C15' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'LC-I-C15' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'LC-I-C15' },
    ],
  },
  {
    courseCode: 'MCD540',
    courseName: 'Biostatistics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C11' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C11' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'LC-I-C11' },
    ],
  },
  {
    courseCode: 'MCO532',
    courseName: 'Advanced Multivariate Analysis',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C11' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C11' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: 'LC-I-C11' },
    ],
  },
  {
    courseCode: 'GLC509',
    courseName: 'Igneous Petrology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: 'AGL-3' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'AGL-3' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: 'AGL-3' },
    ],
  },
  {
    courseCode: 'GLC510',
    courseName: 'Metamorphic Petrology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '16:00', endTime: '16:50', venue: 'AGL-3' },
      { day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'AGL-3' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'AGL-3' },
    ],
  },
  {
    courseCode: 'GLC514',
    courseName: 'Igneous and Metamorphic Petrology Practical',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'Petrology Lab' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'Petrology Lab' },
    ],
  },
  {
    courseCode: 'GLC515',
    courseName: 'Sedimentology and Petroleum Geology Practical',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'Petrology Lab' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'Petrology Lab' },
    ],
  },
  {
    courseCode: 'GLD529',
    courseName: 'Organic Geochemistry',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD530',
    courseName: 'Geodynamics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD540',
    courseName: 'Geomorphology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD551',
    courseName: 'Elements of Rock Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G6' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G6' },
    ],
  },
  {
    courseCode: 'GLO542',
    courseName: 'Remote Sensing and GIS',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'GPC508',
    courseName: 'Earthquake Seismology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'GPC509',
    courseName: 'Geoelectrical Method',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'AGP Annexure Ground Floor' },
      {
        day: 'Wednesday',
        startTime: '17:00',
        endTime: '17:50',
        venue: 'AGP Annexure Ground Floor',
      },
    ],
  },
  {
    courseCode: 'GPC510',
    courseName: 'Well Logging',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      {
        day: 'Wednesday',
        startTime: '16:00',
        endTime: '16:50',
        venue: 'AGP Annexure Ground Floor',
      },
      { day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPC511',
    courseName: 'Seismic Data Acquisition',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'AGP Annexure Ground Floor' },
      {
        day: 'Wednesday',
        startTime: '15:00',
        endTime: '15:50',
        venue: 'AGP Annexure Ground Floor',
      },
    ],
  },
  {
    courseCode: 'GPC512',
    courseName: 'Seismic Data Acquisition Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPC513',
    courseName: 'Geoelectrical Methods Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: 'AGP Annexure Ground Floor' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: 'AGP Annexure Ground Floor' },
    ],
  },
  {
    courseCode: 'GPC515',
    courseName: 'Earthquake Seismology and Well Logging Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: 'AGP 516' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: 'AGP 516' },
    ],
  },
  {
    courseCode: 'MCC511',
    courseName: 'Database Management Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G13' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G13' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G13' },
    ],
  },
  {
    courseCode: 'MCC513',
    courseName: 'Database Management Systems Practical',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Friday', startTime: '10:00', endTime: '10:50', venue: 'NLHC Computer lab 3' },
      { day: 'Friday', startTime: '08:00', endTime: '08:50', venue: 'NLHC Computer lab 3' },
      { day: 'Friday', startTime: '09:00', endTime: '09:50', venue: 'NLHC Computer lab 3' },
    ],
  },
  {
    courseCode: 'MCC535',
    courseName: 'Soft Computing Techniques',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: 'LC-I-C11' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: 'LC-I-C11' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: 'LC-I-C11' },
    ],
  },
  {
    courseCode: 'MCD503',
    courseName: 'Integral Equations and Calculus of Variations',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-C20' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C20' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-C20' },
    ],
  },
  {
    courseCode: 'MCD508',
    courseName: 'Theory of Computation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G11' },
      { day: 'Thursday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G11' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: 'LC-II-G11' },
    ],
  },
  {
    courseCode: 'MCD558',
    courseName: 'Wavelets: Theory and Applications',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'MCO402',
    courseName: 'Modelling and Simulation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G10' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: 'LC-II-G10' },
      { day: 'Friday', startTime: '16:00', endTime: '16:50', venue: 'LC-II-G10' },
    ],
  },
  {
    courseCode: 'CSI101',
    courseName: 'Computer Programming',
    ltp: '2-1-0',
    credits: calculateCredits('2-1-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSI102',
    courseName: 'Computer Programming Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'MCI102',
    courseName: 'Mathematics - II',
    ltp: '3-1-0',
    credits: calculateCredits('3-1-0'),
    slots: [
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'MCI103',
    courseName: 'Numerical Methods',
    ltp: '2-2-0',
    credits: calculateCredits('2-2-0'),
    slots: [
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Friday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHI101',
    courseName: 'Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHI102',
    courseName: 'Physics Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'HSI101',
    courseName: 'Communication Skills',
    ltp: '1-0-2',
    credits: calculateCredits('1-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC201',
    courseName: 'Data Structures',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC204',
    courseName: 'Data Structures Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Monday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC208',
    courseName: 'Theory of Computation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC209',
    courseName: 'Operating Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC211',
    courseName: 'Operating Systems Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSE202',
    courseName: 'Object Oriented Programming',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Tuesday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Wednesday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC301',
    courseName: 'Database Management Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC303',
    courseName: 'Database Management Systems Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'CSC503',
    courseName: 'Algorithmic Graph Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Tuesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC203',
    courseName: 'Digital Circuits and System Design',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC204',
    courseName: 'Digital System Design Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Monday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC206',
    courseName: 'Analog Circuits',
    ltp: '3-1-0',
    credits: calculateCredits('3-1-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC207',
    courseName: 'Electromagnetic Theory',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC210',
    courseName: 'Electronic Devices and Circuits Lab',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC301',
    courseName: 'Principles of Communication Systems',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECC305',
    courseName: 'Communication System Lab',
    ltp: '0-0-3',
    credits: calculateCredits('0-0-3'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'ECO561',
    courseName: 'Embedded System Design',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Wednesday', startTime: '14:00', endTime: '14:50', venue: '' },
    ],
  },
  {
    courseCode: 'EEC204',
    courseName: 'Electrical Machines - I',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Tuesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'EEC274',
    courseName: 'Electrical Machines and Power lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHD502',
    courseName: 'Computational Physics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Tuesday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'MCC203',
    courseName: 'Real Analysis',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'MNC207',
    courseName: 'Underground Metal Mining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Tuesday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Wednesday', startTime: '18:00', endTime: '18:50', venue: '' },
    ],
  },
  {
    courseCode: 'MNC208',
    courseName: 'Underground Coal Mining',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '10:00', endTime: '10:50', venue: '' },
      { day: 'Thursday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'MEC207',
    courseName: 'Dynamics of Machinery',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '10:00', endTime: '10:50', venue: '' },
    ],
  },
  {
    courseCode: 'MEC210',
    courseName: 'Heat Transfer and Fluid Machines Lab',
    ltp: '0-0-2',
    credits: calculateCredits('0-0-2'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'MSC510',
    courseName: 'Corporate Finance',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '14:00', endTime: '14:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Thursday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'MSC512',
    courseName: 'Operations Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Tuesday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Wednesday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'MSC513',
    courseName: 'Marketing Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'ESC503',
    courseName: 'MATLAB Programming for Numerical Computation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Tuesday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Wednesday', startTime: '18:00', endTime: '18:50', venue: '' },
    ],
  },
  {
    courseCode: 'ESC507',
    courseName: 'Municipal Solid Waste Management',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '08:00', endTime: '08:50', venue: '' },
      { day: 'Thursday', startTime: '08:00', endTime: '08:50', venue: '' },
      { day: 'Friday', startTime: '08:00', endTime: '08:50', venue: '' },
    ],
  },
  {
    courseCode: 'PEC206',
    courseName: 'Elements of Petroleum Production Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Tuesday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Wednesday', startTime: '18:00', endTime: '18:50', venue: '' },
    ],
  },
  {
    courseCode: 'PEC207',
    courseName: 'Petroleum Formation Evaluation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '08:00', endTime: '08:50', venue: '' },
      { day: 'Thursday', startTime: '08:00', endTime: '08:50', venue: '' },
      { day: 'Friday', startTime: '08:00', endTime: '08:50', venue: '' },
    ],
  },
  {
    courseCode: 'PHC207',
    courseName: 'Nuclear Science and Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Tuesday', startTime: '18:00', endTime: '18:50', venue: '' },
      { day: 'Wednesday', startTime: '18:00', endTime: '18:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD528',
    courseName: 'Geotechnical Engineering',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: 'AGL-1' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: 'AGL-1' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: 'AGL-1' },
    ],
  },
  {
    courseCode: 'GLD530',
    courseName: 'Geodynamics',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Friday', startTime: '11:00', endTime: '11:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD540',
    courseName: 'Geomorphology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '17:00', endTime: '17:50', venue: '' },
      { day: 'Thursday', startTime: '16:00', endTime: '16:50', venue: '' },
      { day: 'Friday', startTime: '17:00', endTime: '17:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLD544',
    courseName: 'Kinematics of Rock Deformation',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Tuesday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Wednesday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLO542',
    courseName: 'Remote Sensing and GIS',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Wednesday', startTime: '11:00', endTime: '11:50', venue: '' },
      { day: 'Thursday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Friday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'GLO545',
    courseName: 'Radiogenic and Stable Isotope Geology',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '16:00', endTime: '16:50', venue: 'AGL-3' },
      { day: 'Tuesday', startTime: '16:00', endTime: '16:50', venue: 'AGL-3' },
      { day: 'Wednesday', startTime: '16:00', endTime: '16:50', venue: 'AGL-3' },
    ],
  },
  {
    courseCode: 'GPD505',
    courseName: 'Near Surface Geophysics and Geotechnical Modelling',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Tuesday', startTime: '15:00', endTime: '15:50', venue: '' },
      { day: 'Wednesday', startTime: '15:00', endTime: '15:50', venue: '' },
    ],
  },
  {
    courseCode: 'GPO510',
    courseName: 'Strong Motion Seismology and Structural Responses',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Tuesday', startTime: '12:00', endTime: '12:50', venue: '' },
      { day: 'Wednesday', startTime: '12:00', endTime: '12:50', venue: '' },
    ],
  },
  {
    courseCode: 'CEE202',
    courseName: 'Fluid Mechanics and Machines',
    ltp: '3-0-0',
    credits: calculateCredits('3-0-0'),
    slots: [
      { day: 'Monday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Tuesday', startTime: '09:00', endTime: '09:50', venue: '' },
      { day: 'Wednesday', startTime: '09:00', endTime: '09:50', venue: '' },
    ],
  },
];
